//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PMonteurPartie
{
    using PCivilisation;
    using PPartie;
    using PCarte;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MonteurCreationPartie : MonteurCreationPartieAbstraite
	{

        // choix du joueur qui commence la partie en premier
		public override void initialiserJoueurCourant()
		{
            Random random = new Random();
            int num = random.Next(0, _partie._liste_joueurs.Count);
            _partie._joueurCourant = _partie._liste_joueurs[num];
		}

        // constrcuteur du monteur d'une partie
		public MonteurCreationPartie()
		{
		}

	}
}

