//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCarte
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Wrapper;
    using PCase;

    public class Petite : Carte
    {
        // constructeur d'une carte Petite
        public Petite(int nbjoueur):base(25, nbjoueur)
        {
        }
    }
}

