//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PImplEii
{
    using PInterfaces_Fabrique_Abstraite;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class DirecteurEii : Unite
    {
        // constructeur de DirecteurEii avec les caracteristiques associees
        public DirecteurEii(int x, int y)
            : base(x, y)
        {
            _attaque = 0;
            _defense = 2;
            _mouvement = 3;
            _vie = 5;
        }

        // cout de l'unite
        public override int getCout()
        {
            return 200;
        }

    }
}

