//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PImplEii
{
    using PInterfaces_Fabrique_Abstraite;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class EnseignantEii : Unite
    {
        // l'enseignant peut fonder une ville
        public virtual void fonder(int x, int y)
        {
            throw new System.NotImplementedException();
        }

        // cout de l'unite
        public override int getCout()
        {
            return 60;
        }

        // constructeur de EnseignantEii avec les caracteristiques associees
        public EnseignantEii(int x, int y)
            : base(x, y)
        {
            _attaque = 0;
            _defense = 2;
            _mouvement = 2;
            _vie = 1;
        }

    }
}

