//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PImplEii
{
    using PInterfaces_Fabrique_Abstraite;
    using PConstantes;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class EtudiantEii : Unite
    {

        // combat avec une autre unite
        public virtual void combattre()
        {
            throw new System.NotImplementedException();
        }

        // constructeur de EtudiantEii avec les caracteristiques associees
        public EtudiantEii(int x, int y)
            : base(x, y)
        {
            _attaque = 3;
            _defense = 3;
            _mouvement = 2;
            _vie = 10;
        }

        // augmentation de 50% des caracteristiques de defense et d’attaque si directeur sur même case
        public void augmenterCarac()
        {
            if (_defense > 0)
            {
                _defense += (_defense / 2);
            }
            if (_attaque > 0)
            {
                _attaque += (_attaque / 2);
            }
        }

        // cout de l'unite
        public override int getCout()
        {
            return 100;
        }

    }
}

