//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PImplEii
{
	using PInterfaces_Fabrique_Abstraite;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FabriqueUniteEii : FabriqueUnite
	{
        // creation d'un enseignantEii
        public virtual Unite creerEnseignant(int x, int y)
		{
            return new EnseignantEii(x, y);
        }

        // creation d'un DirecteurEii
        public virtual Unite creerDirecteur(int x, int y)
		{
            return new DirecteurEii(x, y);
		}

        // creation d'un etudiantEii
        public virtual Unite creerEtudiant(int x, int y)
		{
            return new EtudiantEii(x, y);
		}

        // constructeur de la fabriqueEii
		public FabriqueUniteEii()
		{
		}

	}
}

