//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PPartie
{
	using PCarte;
	using PJoueur;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Partie
	{
        // numero du tour de la partie
		public int _tour
		{
			get;
			set;
		}

        // joueur courant de la partie
        public Joueur _joueurCourant
		{
			get;
			set;
		}

        // nb joueurs total de la partie
        public int _nbJoueur
		{
            get { return _liste_joueurs.Count; }
		}

        // liste des joueurs de la partie
		public List<Joueur> _liste_joueurs
		{
			get;
			set;
		}

        // carte de la partie
		public Carte _carte
		{
			get;
			set;
		}

        // constructeur d'une partie
        public Partie()
        {
            _liste_joueurs = new List<Joueur>();
        }

        // passer au tour suivant
		public void tourSuivant()
		{
			_tour++;
		}
	}
}

