//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PInterfaces_Fabrique_Abstraite
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface FabriqueUnite 
	{
        // creation d'un enseignant
        Unite creerEnseignant(int x, int y);

        // creation d'un directeur
        Unite creerDirecteur(int x, int y);

        // creation d'un etudiant
        Unite creerEtudiant(int x, int y);

	}
}

