//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PConstantes
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Direction
	{
        public const int EST = 0;
        public const int NORD = 1;
        public const int OUEST = 2;
        public const int SUD = 3;
	}
}

