//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PConstantes
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class TypeCase
	{
        public const int DESERT = 0;
        public const int DESERT_FER = 1;
        public const int DESERT_NOURRITURE = 2;
        public const int MONTAGNE = 3;
        public const int MONTAGNE_FER = 4;
        public const int MONTAGNE_NOURRITURE = 5;
        public const int PLAINE = 6;
        public const int PLAINE_FER = 7;
        public const int PLAINE_NOURRITURE = 8;
	}
}

