//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PConstantes
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class TypeCarte
	{
        public const int PETITE = 25;
        public const int NORMALE = 100;
	}
}

