//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCarte
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Normale : Carte
    {
        // constructeur d'un carte Normale
        public Normale(int nbjoueur):base(100,nbjoueur)
        {
        }
    }
}

