//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PImplInfo
{
	using PInterfaces_Fabrique_Abstraite;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FabriqueUniteInfo : FabriqueUnite
	{
        // creation d'un ensignantInfo
        public virtual Unite creerEnseignant(int x, int y)
		{
            return new EnseignantInfo(x,y);
		}

        // creation d'un directeurInfo
        public virtual Unite creerDirecteur(int x, int y)
		{
            return new DirecteurInfo(x, y);
        }

        // creation d'un etudiantInfo
        public virtual Unite creerEtudiant(int x, int y)
		{
            return new EtudiantInfo(x, y);
        }

        // constructeur de la fabriqueInfo
		public FabriqueUniteInfo()
		{
		}

	}
}

