//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCase
{
    using System;
    using PInterfaces_Fabrique_Abstraite;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using PConstantes;
    using PImplEii;
    using PImplInfo;

    public abstract class Case
    {
        // capacite en nourriture
        public int _nourriture
        {
            get;
            set;
        }

        // capacite en fer
        public int _fer
        {
            get;
            set;
        }

        // retourne capacite en nourriture
        public abstract int getNourriture();

        // retourne capacite en fer
        public abstract int getFer();

        // constructeur de case
        public Case()
        {
            _fer = 0;
            _nourriture = 0;
        }
    }
}

