//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCase
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Decorateur_Ressource : Case
	{
        // case que le decorateur possede
		public Case _case
		{
			get;
			set;
		}

        // constructeur du decorateur
		public void Decorateur_ressource()
		{
        }
	}
}

