//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCase
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Desert : Case
	{
        // constructeur de la case Desert
		public Desert()
		{
            _fer = 1;
            _nourriture = 0;
		}

        // capacite de nourriture
        public override int getNourriture()
        {
            return _nourriture;
        }

        // capacite en fer
        public override int getFer()
        {
            return _fer;
        }
	}
}

