//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCase
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Fer : Decorateur_Ressource
	{
        // constructeur de Fer
        public Fer(Case case_a_decorer)
		{
            _case = case_a_decorer;
		}

        // capacite en nourriture
        public override int getNourriture()
        {
            return _case._nourriture;
        }

        // capacite en fer
        public override int getFer()
        {
            return (_case._fer+2);
        }
	}
}

