//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCase
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Montagne : Case
	{
        // constructeur de Montagne
		public Montagne()
		{
            _fer = 3;
            _nourriture=0;
		}

        // capacite nourriture
        public override int getNourriture()
        {
            return _nourriture;
        }

        // capacite de fer
        public override int getFer()
        {
            return _fer;
        }

	}
}

