//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCivilisation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Eii : Civilisation
	{
        // constructeur de la Civilisation Eii
		public Eii(string nom):base(nom)
		{
		}

	}
}

