//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCivilisation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using PJoueur;

	public abstract class Civilisation
	{
        // nom de la civilisation
		public string _nomCivilisation
		{
			get;
			set;
		}

        // liste de villes que possede la civilisation
		public List<Ville> _villes
		{
			get;
			set;
		}

        // constructeur de la Civilisation
		protected Civilisation(string nom)
		{
            _nomCivilisation = nom;
            _villes = new List<Ville>(); ;
    	}

	}
}

