//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PCivilisation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Info : Civilisation
	{
        // constructeur de la Civilisation Info
        public Info(string nom):base(nom)
		{
        }
	}
}

